Ensure that a string value is passed to str()
This resolves the following error seen in GitHub Actions runs:

src/vdp_scanner.py:258: error: Argument 2 to "str" has incompatible type "Optional[str]"; expected "str"

This error flags because the `encoding` property of a response object is not
guaranteed to be set, but the str() function requires a string value for its
second argument.